
package com.ims.component;


public class Table extends javax.swing.JPanel {

    /**
     * Creates new form Table
     */
    public Table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        computerStudentsTable = new rojeru_san.complementos.RSTableMetro();

        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 204, 204)));
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        computerStudentsTable.setAutoCreateRowSorter(true);
        computerStudentsTable.setForeground(new java.awt.Color(255, 255, 255));
        computerStudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.N", "Admission Date", "Student Name", "Student Contact", "Course Name", "Course Fee", "Due Ammount", "1st payment Date", "1st payment amt", "2nd payment date", "2nd payment amt", "3rd payment date", "3rd payment amt", "4th payment date", "4th payment amt", "Student DOB", "Parent's Name", "Parent's Contact", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        computerStudentsTable.setAutoResizeMode(0);
        computerStudentsTable.setColorBackgoundHead(new java.awt.Color(51, 153, 0));
        computerStudentsTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        computerStudentsTable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        computerStudentsTable.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        computerStudentsTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        computerStudentsTable.setFuenteHead(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        computerStudentsTable.setRowHeight(40);
        jScrollPane2.setViewportView(computerStudentsTable);
        if (computerStudentsTable.getColumnModel().getColumnCount() > 0) {
            computerStudentsTable.getColumnModel().getColumn(0).setMinWidth(50);
            computerStudentsTable.getColumnModel().getColumn(0).setMaxWidth(100);
            computerStudentsTable.getColumnModel().getColumn(1).setMinWidth(100);
            computerStudentsTable.getColumnModel().getColumn(1).setMaxWidth(400);
            computerStudentsTable.getColumnModel().getColumn(2).setMinWidth(100);
            computerStudentsTable.getColumnModel().getColumn(2).setMaxWidth(400);
            computerStudentsTable.getColumnModel().getColumn(3).setMinWidth(150);
            computerStudentsTable.getColumnModel().getColumn(3).setMaxWidth(400);
            computerStudentsTable.getColumnModel().getColumn(4).setMinWidth(100);
            computerStudentsTable.getColumnModel().getColumn(4).setMaxWidth(400);
            computerStudentsTable.getColumnModel().getColumn(5).setMinWidth(100);
            computerStudentsTable.getColumnModel().getColumn(5).setMaxWidth(400);
            computerStudentsTable.getColumnModel().getColumn(6).setMinWidth(100);
            computerStudentsTable.getColumnModel().getColumn(6).setMaxWidth(400);
            computerStudentsTable.getColumnModel().getColumn(7).setMinWidth(150);
            computerStudentsTable.getColumnModel().getColumn(7).setMaxWidth(500);
            computerStudentsTable.getColumnModel().getColumn(8).setMinWidth(150);
            computerStudentsTable.getColumnModel().getColumn(8).setMaxWidth(500);
            computerStudentsTable.getColumnModel().getColumn(9).setMinWidth(150);
            computerStudentsTable.getColumnModel().getColumn(9).setMaxWidth(500);
            computerStudentsTable.getColumnModel().getColumn(10).setMinWidth(150);
            computerStudentsTable.getColumnModel().getColumn(10).setMaxWidth(500);
            computerStudentsTable.getColumnModel().getColumn(11).setMinWidth(150);
            computerStudentsTable.getColumnModel().getColumn(11).setMaxWidth(500);
            computerStudentsTable.getColumnModel().getColumn(12).setMinWidth(150);
            computerStudentsTable.getColumnModel().getColumn(12).setMaxWidth(500);
            computerStudentsTable.getColumnModel().getColumn(13).setMinWidth(150);
            computerStudentsTable.getColumnModel().getColumn(13).setMaxWidth(500);
            computerStudentsTable.getColumnModel().getColumn(14).setMinWidth(150);
            computerStudentsTable.getColumnModel().getColumn(14).setMaxWidth(500);
            computerStudentsTable.getColumnModel().getColumn(15).setMinWidth(100);
            computerStudentsTable.getColumnModel().getColumn(15).setMaxWidth(400);
            computerStudentsTable.getColumnModel().getColumn(16).setMinWidth(100);
            computerStudentsTable.getColumnModel().getColumn(16).setMaxWidth(400);
            computerStudentsTable.getColumnModel().getColumn(17).setMinWidth(100);
            computerStudentsTable.getColumnModel().getColumn(17).setMaxWidth(400);
            computerStudentsTable.getColumnModel().getColumn(18).setMinWidth(100);
            computerStudentsTable.getColumnModel().getColumn(18).setMaxWidth(400);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 100, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked

       

    }//GEN-LAST:event_jScrollPane2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSTableMetro computerStudentsTable;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
